### ISSUE TITLE
As a player who joins the game, I want to be able to register as a user with a username to participate in the game.

### ISSUE THREAD

**Issue by glt-cs** [sopra-fs23-group-28/sopra-fs23-group-28-server#1]
- [x] sopra-fs23-group-28/sopra-fs23-group-28-client#23
- [x] sopra-fs23-group-28/sopra-fs23-group-28-server#14
- [x] sopra-fs23-group-28/sopra-fs23-group-28-client#22
- [x] sopra-fs23-group-28/sopra-fs23-group-28-client#21

**Comment by so-ri** [comment]
closed with 
https://github.com/sopra-fs23-group-28/sopra-fs23-group-28-client/commit/3e43cef64e1484462a4f5475177cfd0f68c1fef1
https://github.com/sopra-fs23-group-28/sopra-fs23-group-28-client/commit/8c548d22c9007e3a161b0fe3c60577a8fd3cc93c
https://github.com/sopra-fs23-group-28/sopra-fs23-group-28-server/commit/79c5286272b5196dc49df7c313d6a6b9951a652a
https://github.com/sopra-fs23-group-28/sopra-fs23-group-28-client/commit/11d9e409f6f8bfb0112e26878e3c2e4830670471
