### ISSUE TITLE
As a player who won 2 quiz rounds in a row, I get to punish another player, in order to make the game more competitive.

### ISSUE THREAD

**Issue by glt-cs** [sopra-fs23-group-28/sopra-fs23-group-28-server#10]
- [x] sopra-fs23-group-28/sopra-fs23-group-28-client#5
- [x] sopra-fs23-group-28/sopra-fs23-group-28-server#48
- [x] sopra-fs23-group-28/sopra-fs23-group-28-server#47
- [x] sopra-fs23-group-28/sopra-fs23-group-28-server#46

**Comment by so-ri** [comment]
optional, won't do

**Comment by so-ri** [comment]
optional, won't do
