### ISSUE TITLE
As a player who won 4 quizzes in a row, i receive a gadget that i can use on myself for a small push ahead or as punishment for another player

### ISSUE THREAD

**Issue by glt-cs** [sopra-fs23-group-28/sopra-fs23-group-28-server#11]
- [x] sopra-fs23-group-28/sopra-fs23-group-28-server#53
- [x] sopra-fs23-group-28/sopra-fs23-group-28-server#52
- [x] sopra-fs23-group-28/sopra-fs23-group-28-client#4
- [x] sopra-fs23-group-28/sopra-fs23-group-28-server#50

**Comment by so-ri** [comment]
optional, won't do
