### ISSUE TITLE
 As a player and after the threshold for a win has been met or the defined number of rounds have elapsed, I want to see an overview of the game stats and the scoreboard.

### ISSUE THREAD

**Issue by glt-cs** [sopra-fs23-group-28/sopra-fs23-group-28-server#12]
- [x] sopra-fs23-group-28/sopra-fs23-group-28-client#1
- [x] sopra-fs23-group-28/sopra-fs23-group-28-client#2
- [x] sopra-fs23-group-28/sopra-fs23-group-28-client#3
- [x] sopra-fs23-group-28/sopra-fs23-group-28-server#54
- [x] #64
- [x] #74
- [x] #75
- [x] #86

**Comment by so-ri** [comment]
closed with e35efa2a2620016b53c07d79f18d9ae11fa5b018
