### ISSUE TITLE
As a registered player I want to be able to host a session to play with friends.

### ISSUE THREAD

**Issue by glt-cs** [sopra-fs23-group-28/sopra-fs23-group-28-server#3]
- [x] sopra-fs23-group-28/sopra-fs23-group-28-server#19
- [x] sopra-fs23-group-28/sopra-fs23-group-28-client#19
- [x] sopra-fs23-group-28/sopra-fs23-group-28-server#21
- [x] sopra-fs23-group-28/sopra-fs23-group-28-server#22
