### ISSUE TITLE
As the creator of the lobby and with everyone ready to play, I want to be able to start the game.

### ISSUE THREAD

**Issue by glt-cs** [sopra-fs23-group-28/sopra-fs23-group-28-server#4]
- [x] sopra-fs23-group-28/sopra-fs23-group-28-client#18
- [ ] sopra-fs23-group-28/sopra-fs23-group-28-client#17
- [x] sopra-fs23-group-28/sopra-fs23-group-28-server#25
- [x] sopra-fs23-group-28/sopra-fs23-group-28-server#26

**Comment by iKusii** [comment]
closed with commit https://github.com/sopra-fs23-group-28/sopra-fs23-group-28-client/commit/36e0c6dd37f8af1c8ebc41bedffe932f1db4b4a8
