### ISSUE TITLE
After starting the game flow, the quiz questions, game logic, camel race and the users in the round are being displayed.

### ISSUE THREAD

**Issue by glt-cs** [sopra-fs23-group-28/sopra-fs23-group-28-server#6]
- [ ] sopra-fs23-group-28/sopra-fs23-group-28-client#14
- [ ] sopra-fs23-group-28/sopra-fs23-group-28-client#13
- [x] sopra-fs23-group-28/sopra-fs23-group-28-server#32
- [x] #65

**Comment by iKusii** [comment]
closed with commit https://github.com/sopra-fs23-group-28/sopra-fs23-group-28-client/commit/36e0c6dd37f8af1c8ebc41bedffe932f1db4b4a8
