### ISSUE TITLE
As a player before a round starts, I want to be able to vote for a category of questions in order to have an additional feeling of interaction. 

### ISSUE THREAD

**Issue by glt-cs** [sopra-fs23-group-28/sopra-fs23-group-28-server#7]
- [x] sopra-fs23-group-28/sopra-fs23-group-28-client#11
- [x] sopra-fs23-group-28/sopra-fs23-group-28-server#36
- [x] sopra-fs23-group-28/sopra-fs23-group-28-server#35
- [x] sopra-fs23-group-28/sopra-fs23-group-28-client#12
- [x] sopra-fs23-group-28/sopra-fs23-group-28-server#33
- [x] #78
- [x] #79

**Comment by iKusii** [comment]
closed with commit https://github.com/sopra-fs23-group-28/sopra-fs23-group-28-client/commit/36e0c6dd37f8af1c8ebc41bedffe932f1db4b4a8

**Comment by so-ri** [comment]
closed with 409a4a96de979b6e66f5f444e8578f2cc829a002
