### ISSUE TITLE
 As a player who just lost a quiz round and had to take steps back, I want to be able to determine how many steps the next loser must go back (might be me again), in order to make the experience competitive and exciting.

### ISSUE THREAD

**Issue by glt-cs** [sopra-fs23-group-28/sopra-fs23-group-28-server#9]
- [x] sopra-fs23-group-28/sopra-fs23-group-28-client#6
- [x] sopra-fs23-group-28/sopra-fs23-group-28-client#7
- [x] sopra-fs23-group-28/sopra-fs23-group-28-client#8
- [x] sopra-fs23-group-28/sopra-fs23-group-28-client#9
- [x] #66
- [x] #67

**Comment by so-ri** [comment]
50be8ff28a7d069be8b771595953b842d2e8df8a
